#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# Kill already running process
_ps=(waybar dunst xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
/usr/lib/xfce-polkit/xfce-polkit &

# xdg desktop wlr thing for screen sharing
/usr/lib/xdg-desktop-portal-wlr &

# Lauch notification daemon (mako)
dunst & #-config $HOME/.dunstrc &

# Start network manager applet
nm-applet --indicator &
gammastep-indicator &
waybar -c ~/.config/sway/waybar/config -s ~/.config/sway/waybar/style.css &

~/.config/sway/scripts/swayidle.sh &
